site_name: PME-toolkit
site_description: Parametric Model Embedding toolkit for design-space dimensionality reduction
site_url: https://cnr-inm-mao.github.io/pme-toolkit/
use_directory_urls: true

theme:
  name: material
  language: en

  logo: assets/logos/logo-wave-white-nobg.png
  favicon: assets/logos/logo-wave-nobg.png
  
nav:
  - Home: index.md
  - Quickstart: quickstart.md

  - Core concepts:
      - Workflow: workflow.md
      - Input data: input_data.md
      - Configuration: config_spec.md

  - Execution:
      - Benchmarks: benchmarks.md
      - Datasets: datasets.md
      - Reproducibility: reproducibility.md

  - Backmapping:
      - Overview: backmapping.md
      - Configuration: backmapping_config.md

  - Visualization: visualization.md

  - API:
      - Python API: python_api.md
      - MATLAB API: matlab_api.md

  - Citation: citation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
